codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 5  # Wait for all Python versions to report
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        only_pulls: true       # Only use in PRs
        informational: false   # Block PR if fails
    patch:
      default:
        target: 100%            # New code should have 100% coverage
        threshold: 1%
        base: auto
        only_pulls: true       # Only use in PRs
        informational: false   # Block PR if fails
    changes: yes               # Block if coverage on files changes decreases

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false  # Post comment even if coverage doesn't change
  require_base: true       # Require base branch coverage
  require_head: true       # Require head branch coverage
  after_n_builds: 5        # Wait for all Python versions before commenting

github_checks:
  annotations: true        # Add annotations to the PR

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "setup.py"
