name: Publish to TestPyPI

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      version_suffix:
        description: 'Dev version suffix (e.g., dev0, rc1)'
        required: true
        default: 'dev0'

  # Optionally trigger on pushes to specific branches
  # Uncomment to enable
  # push:
  #   branches:
  #     - 'staging'
  #     - 'release/*'

jobs:
  # Skip PR check for manual triggers
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine setuptools wheel

      # Use dynamic versioning with the provided suffix
      - name: Prepare version
        id: prepare-version
        run: |
          # Get base version from pyproject.toml
          BASE_VERSION=$(grep -Po '(?<=version = ")[^"]*' pyproject.toml)
          DEV_SUFFIX="${{ github.event.inputs.version_suffix }}"

          # For manual triggers, use the provided suffix
          if [ -n "$DEV_SUFFIX" ]; then
            NEW_VERSION="${BASE_VERSION}.${DEV_SUFFIX}"
          else
            # For automatic triggers, use the short commit SHA
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            NEW_VERSION="${BASE_VERSION}.dev${SHORT_SHA}"
          fi

          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "Version set to: $NEW_VERSION"

          # Temporarily update version in pyproject.toml
          sed -i "s/version = \"$BASE_VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
